### ISSUE TITLE
REFERENCE ID

### ISSUE THREAD

**Issue by JacobRimith** [rikulo/xml-crypto#3]
As I can sign without the attributes Id = "_ 0" to the node I am signing. Also in the references of the firm the following URI attribute = "#_ 0" is added. There is some way that this does not come [out.[](url)](![CapturaFirma](https://user-images.githubusercontent.com/90999774/193195020-c191e125-8b1f-41c6-bcd1-49bcb1c8f030.PNG))

**Comment by scribetw** [comment]
Maybe you want to sign the root node? https://github.com/yaronn/xml-crypto/issues/122

**Comment by JacobRimith** [comment]
Assuming that this /* is to sign the initial node, the ID = "_ 0" attribute is still generated in the signed node.

**Comment by JacobRimith** [comment]
It was resolved by establishing the _**isemptyuri**_ property in _**True**_ by creating the reference.

![CapturaFirma4](https://user-images.githubusercontent.com/90999774/193307547-0f2ae2fe-3387-4410-85c4-6a877deedd8c.PNG)
