### ISSUE TITLE
Please port to the new version of  xpath_selector

### ISSUE THREAD

**Issue by KristijanZic** [rikulo/xml-crypto#4]
There is a new major version of  xpath_selector and it conflicts with multiple very popular other packages that depend on the new major version.

When I go `flutter pub add xml_crypto` I get this error:
```
Because flutter_native_splash >=2.2.3 depends on xml ^6.1.0 and xpath_selector <3.0.0 depends on xml ^5.3.1, flutter_native_splash >=2.2.3 is incompatible with xpath_selector <3.0.0.
And because every version of xml_crypto depends on xpath_selector ^2.2.4, flutter_native_splash >=2.2.3 is incompatible with xml_crypto.
So, because supabase_studio depends on both flutter_native_splash ^2.2.16 and xml_crypto any, version solving failed.
pub finished with exit code 65
```

After I removed the flutter_native_splash dependency I got this:
```
Because flutter_local_notifications >=13.0.0 depends on flutter_local_notifications_linux ^3.0.0 which depends on dbus ^0.7.8, flutter_local_notifications >=13.0.0 requires dbus ^0.7.8.
And because dbus >=0.7.4 depends on xml ^6.1.0, flutter_local_notifications >=13.0.0 requires xml ^6.1.0.
And because every version of xml_crypto depends on xpath_selector ^2.2.4 which depends on xml ^5.3.1, flutter_local_notifications >=13.0.0 is incompatible with xml_crypto.
So, because supabase_studio depends on both flutter_local_notifications ^13.0.0 and xml_crypto any, version solving failed.
pub finished with exit code 65
```

**Comment by scribetw** [comment]
Hi, since `xpath_selector` 3.0.1 still depends on xml ^5.3.1, the upcoming new version of xml-crypto still can't solve your dependency issue.
I asked the author to upgrade the dependency too.

In the mean time, you can try `dependency_overrides` in pubspec.yaml:
```
dependency_overrides:
  xml: ^6.1.0
```

**Comment by scribetw** [comment]
v3.0.1 released

**Comment by KristijanZic** [comment]
You rock! I kinda did a quick and dirty port of both packages myself a few days ago but I honestly don't understand that ins and outs of this code so this is probably waaay better. :D Thank you so much!
I'm blown away by how quickly this got ported by you guys!
